# Site settings
title: The Cobwebbed Coder
email: michalportes1@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Michal Porteš
baseurl: "" # the subpath of your site, e.g. /blog
url: https://mportesdev.github.io
github_username: mportesdev
stackoverflow:
  id: 8795073
  username: mportes
disqus:
  shortname: mportesdev

# Build settings
theme: minima
plugins:
  - jekyll-feed
show_excerpts: true
header_pages:
  - about.md

exclude:
  - README.md
